version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HelloWorld11"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vjmlnts0l1nb"
s3_prefix = "HelloWorld11"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=393190729721.dkr.ecr.us-east-2.amazonaws.com/gleb_hello_world3"]
confirm_changeset = true
